### ISSUE TITLE
Peer to Peer code review

### ISSUE THREAD

**Issue by taldr27** [Javivy/capstone-1#2]
Highlights of your project: 
- An understandable HTML structure
- Good class names

We have some small suggestions to improve your project:
- Kindly try to use a `max-width` property for your images so that the images have a size limit.

Keep doing great. 👍

**Comment by Miliyonayalew** [comment]
## Javier you did a great job 💯 🔥  Keep up thriving 👍  
- I like all styles you used for this capstone project like, the fixed navbar for both desktop and mobile versions, hover animation, and the outline box shadow for the speaker and main program section, anyhow I have one piece of feedback for you, 
- On the mobile version; the partner section on the design part is not displayed so check out the Condy Shin design and make it that section display none using CSS.
